services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: speech-postgres
    environment:
      POSTGRES_DB: speech_to_text
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for BullMQ
  redis:
    image: redis:7-alpine
    container_name: speech-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Node.js Backend API
  backend:
    image: node:18-alpine
    container_name: speech-backend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/speech_to_text
      - REDIS_URL=redis://redis:6379
      - WHISPER_SERVICE_URL=http://whisper-service:8000
      - USE_DOCKER_WHISPER=false
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      whisper-service:
        condition: service_started
    restart: unless-stopped

  # WhisperX service (without model initialization for testing)
  whisper-service:
    build:
      context: ./whisper-service
      dockerfile: Dockerfile.cpu
    container_name: speech-whisper
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_MODEL_INIT=true
      - FORCE_CPU=true
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Next.js Frontend
  frontend:
    image: node:18-alpine
    container_name: speech-frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  whisper_models:

networks:
  default:
    name: speech-network